color:
  brandStrength: 0.1764494578819722
  saturation: 0.7697878680191934
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.1385578240733594
  rhythmicContrast: 0.1443410019855946
title: darthvid
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.60308
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: darthvid
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.35271265800111
