name: darthvid
favicon: null
layout_spectrum: 0.60308
typography_spectrum: 0.35271265800111
title: darthvid
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1764494578819722
  lightness: 0.1385578240733594
  saturation: 0.7697878680191934
  rhythmicContrast: 0.1443410019855946
purpose: []
