name: darthvid
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35271265800110996
title: darthvid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1764494578819722
  lightness: 0.13855782407335937
  saturation: 0.7697878680191934
  rhythmicContrast: 0.14434100198559463
purpose: []
