typography_spectrum: 0.35271265800111
content_rating:
  adult: false
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1764494578819722
  lightness: 0.1385578240733594
  saturation: 0.7697878680191934
  rhythmicContrast: 0.1443410019855946
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.60308
analytics:
  google: UA-1020096-2
  facebook: null
  twitter: null
author:
  name: darthvid
  url: darthvid.com
name: darthvid
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: tusktowall
    url: 'https://tusktowall.darthvid.com'
    type: external
  - name: timeline
    url: 'http://timeline.darthvid.com/'
    type: external
  - name: mastodon
    url: 'https://niu.moe/@darthvid'
    type: external
  - name: twitter
    url: 'https://twitter.com/darthvid'
    type: external
  - name: about
    id: c3a1ce5e-9ee6-4bcf-973f-c12ebb984c29
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: darthvid
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bffbea2-46e7-4c84-99bd-f35a72418de0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0bffbea2-46e7-4c84-99bd-f35a72418de0.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: personal dumping ground of stuff
purpose: []
github: true
